name: Build Native Lib
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r25c
      - name: Build
        run: |
          ${{ steps.ndk.outputs.ndk-path }}/ndk-build \
            NDK_PROJECT_PATH=. \
            APP_ABI=armeabi-v7a \
            APP_PLATFORM=android-24 \
            NDK_OUT=out \
            NDK_LIBS_OUT=libs
      - uses: actions/upload-artifact@v4
        with:
          name: libflexcitymod
          path: libs/armeabi-v7a/libflexcitymod.so
